# syntax=docker/dockerfile:1
FROM public.ecr.aws/lambda/nodejs:14

WORKDIR $LAMBDA_TASK_ROOT

# Workaround for conditional COPY - https://stackoverflow.com/a/46801962
COPY package*.json ./
RUN [ -f package-lock.json ] && npm ci || echo Skip

COPY . .

# https://aws.amazon.com/premiumsupport/knowledge-center/lambda-deployment-package-errors/
RUN find . -type d -exec chmod 755 {} \;
RUN find . -type f -exec chmod 644 {} \;

ENV NODE_ENV=production

CMD [ "index.handler" ]
